# Generated by Django 3.2 on 2021-04-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_num', models.CharField(max_length=10, verbose_name='номер аудитории')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.CharField(default='Главный корпус', max_length=40, verbose_name='корпус')),
                ('address', models.CharField(default='Большая Садовая ул. 69', max_length=120, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Cafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafedra_name', models.CharField(max_length=80, verbose_name='название кафедры')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=80, verbose_name='название факультета')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='аббревиатура')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10, verbose_name='название группы')),
                ('year', models.IntegerField(verbose_name='курс')),
                ('cafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.cafedra')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название пары')),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, verbose_name='вид занятия')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=80, verbose_name='должность')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='с:')),
                ('time_until', models.TimeField(verbose_name='до:')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NN-препод.', max_length=40, verbose_name='имя')),
                ('last_name', models.CharField(max_length=40, null=True, verbose_name='фамилия')),
                ('patronym', models.CharField(max_length=40, null=True, verbose_name='отчество')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='professors', to='api.position')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='чётная/нечётная неделя')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='день недели')),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.auditory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.group')),
                ('lesson_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.lessontype')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.lessonname')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.professor')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='cafedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafedras', to='api.faculty'),
        ),
        migrations.AddField(
            model_name='auditory',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditories', to='api.building'),
        ),
    ]
