# Generated by Django 3.2 on 2021-04-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day', 'timetable']},
        ),
        migrations.RenameField(
            model_name='cafedra',
            old_name='cafedra_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lessontype',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='pos_name',
            new_name='name',
        ),
    ]
