# Generated by Django 3.2 on 2021-04-15 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210415_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='курс'),
        ),
    ]
